### ISSUE TITLE
Metrics and Statisitcs

### ISSUE THREAD

**Issue by DarthMax** [FHG-IMW/aeternitas#2]
Provide a API to access Æternitas' metrics

## Metrics stored in redis
Grouped by pollable class
 - [x]  job execution count 
 - [x]  failed job count, failure_ratio
 - [x]  ignored errors
 - [x]  deactivations
 - [x]  execution time
 - [x] guard
 - [x] waited
 - [x]  guard wait sleep
 - [x]  guard timeout exceeded

## Data statistics
 - [ ] number of sources (per pollable class)
 - [ ] pollables created (per pollable class)
 - [ ] future pollings (per pollable class)

**Comment by tamaloa** [comment]
To avoid an ever growing Redis instance we will expire metric values/counters as following:

| resolution  | expire after |
| ------------- | ------------- |
| minute  | 3 days  |
| 10 minute | 14 days |
| hour | 2 months |
| day | never |

After implementing please gather metrics for a 2 months duration for a single pollable class assuming it's job runs once every second (including all kinds of failure states) to get a worst case baseline for the memory and storage requirements of Redis.
